version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nexerp_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexerp
    ports:
      - "5432:5432"
    volumes:
      - nexerp_pgdata:/var/lib/postgresql/data

volumes:
  nexerp_pgdata:
